// ====================
// DO NOT EDIT THIS FILE!
// This file is autogenerated and will be overwritten during generation!
// ====================

import { z } from 'zod'

// the create schema for table repository
export const repositoryInputSchemaGen = z.object({
	created: z.string().datetime().optional(),
	details: z.object({}).passthrough(),
	githubId: z.number(),
	name: z.string(),
	topics: z.string().array(),
	url: z.string().url(),
	uuid: z.unknown(),
})

// the select schema for table repository
export const repositoryOutputSchemaGen = z.object({
	created: z.string().datetime().optional(),
	details: z.object({}).passthrough(),
	githubId: z.number(),
	name: z.string(),
	topics: z.string().array(),
	url: z.string().url(),
	uuid: z.unknown(),
})
