/* eslint-disable */
/* prettier-ignore */
import type { TadaDocumentNode, $tada } from 'gql.tada';

declare module 'gql.tada' {
 interface setupCache {
    "\n    query getPost($slug: String!) {\n        publication(host: \"alexwhiteside.dev/blog\") {\n            id\n            post(slug: $slug) {\n                slug\n                id\n                publishedAt\n                readTimeInMinutes\n                canonicalUrl\n                coverImage {\n                    url\n                }\n                title\n                updatedAt\n                subtitle\n                brief\n                tags {\n                    name\n                    slug\n                }\n                url\n                reactionCount\n                content {\n                    markdown\n                }\n                features {\n                    tableOfContents {\n                        items {\n                            id\n                            level\n                            slug\n                            title\n                            parentId\n                        }\n                    }\n                }\n            }\n        }\n    }\n":
      TadaDocumentNode<{ publication: { id: string; post: { slug: string; id: string; publishedAt: string; readTimeInMinutes: number; canonicalUrl: string | null; coverImage: { url: string; } | null; title: string; updatedAt: string | null; subtitle: string | null; brief: string; tags: { name: string; slug: string; }[] | null; url: string; reactionCount: number; content: { markdown: string; }; features: { tableOfContents: { items: { id: string; level: number; slug: string; title: string; parentId: string | null; }[]; }; }; } | null; } | null; }, { slug: string; }, void>;
    "\n    query getPosts {\n        publication(host: \"alexwhiteside.dev/blog\") {\n            id\n            posts(first: 10) {\n                edges {\n                    node {\n                        id\n                        slug\n                        coverImage{\n                            url\n                        }\n                        updatedAt\n                        publishedAt\n                        readTimeInMinutes\n                        canonicalUrl\n                        title\n                        subtitle\n                        brief\n                        tags {\n                            name\n                            slug\n                        }\n                        url\n                        reactionCount\n                    }\n                }\n            }\n        }\n    }\n":
      TadaDocumentNode<{ publication: { id: string; posts: { edges: { node: { id: string; slug: string; coverImage: { url: string; } | null; updatedAt: string | null; publishedAt: string; readTimeInMinutes: number; canonicalUrl: string | null; title: string; subtitle: string | null; brief: string; tags: { name: string; slug: string; }[] | null; url: string; reactionCount: number; }; }[]; }; } | null; }, {}, void>;
    "\n    query getPostFromId($id: ID!) {\n            post(id: $id) {\n                id\n                slug  \n                url\n             \n        }\n    }\n":
      TadaDocumentNode<{ post: { id: string; slug: string; url: string; } | null; }, { id: string; }, void>;
    "{\n  publication(host: \"alexwhiteside.dev/blog\") {\n    series(slug: \"featured\") {\n      posts(first: 4) {\n        edges {\n          node {\n            id\n            slug\n            title\n            subtitle\n            url\n          }\n        }\n      }\n    }\n  }\n}":
      TadaDocumentNode<{ publication: { series: { posts: { edges: { node: { id: string; slug: string; title: string; subtitle: string | null; url: string; }; }[]; }; } | null; } | null; }, {}, void>;
  }
}
