// ====================
// DO NOT EDIT THIS FILE!
// This file is autogenerated and will be overwritten during generation!
// ====================

import {z} from "zod";
import {recordId} from "../recordSchema.js"

// the create schema for table resource
export const resourceInputSchemaGen = z.object({
in: recordId('repository'),
  kind: z.string(),
  out: recordId('text'),
  url: z.string(),
  uuid: z.unknown()
});

// the select schema for table resource
export const resourceOutputSchemaGen = z.object({
in: recordId('repository'),
  kind: z.string(),
  out: recordId('text'),
  url: z.string(),
  uuid: z.unknown()
});
